name: reviewdog / hadolint

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/hadolint.yml

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
