name: reviewdog / hadolint

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/hadolint.yml

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
