name: reviewdog / shellcheck

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - '*.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.19.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
