name: reviewdog / shellcheck

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - '*.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
