name: reviewdog / shellcheck

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - '*.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
