name: reviewdog / shellcheck

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - '*.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.23.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
