name: validate docker-compose.yml

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: validate
        run: |
          docker-compose -f docker-compose.yml config
