name: validate docker-compose.yml

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: validate
        run: |
          docker-compose -f docker-compose.yml config
