name: validate docker-compose.yml

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: validate
        run: |
          docker-compose -f docker-compose.yml config
