name: validate docker-compose.yml

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: validate
        run: |
          docker-compose -f docker-compose.yml config
